# Generated by Django 2.2.5 on 2019-09-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20190910_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='password'),
        ),
    ]
