# Generated by Django 2.2.5 on 2019-09-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_auto_20190913_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='public',
            field=models.BooleanField(default=False, help_text='Данный пользователь может проходить закрытые тесты других отделов.', verbose_name='Общедоступный'),
        ),
    ]
