# Generated by Django 2.2.5 on 2019-09-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_profile_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='points',
            field=models.PositiveIntegerField(default='1', verbose_name='Очки за частично правильные ответы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='departament',
            field=models.ManyToManyField(help_text='Данный пользователь сможет проходить закрытые тесты выбранных здесь групп.', to='testing.Departament', verbose_name='Отделы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='public',
            field=models.BooleanField(default=False, help_text='Данный пользователь будет доступен администраторам других отделов.', verbose_name='Общедоступный'),
        ),
    ]
