# Generated by Django 2.2.5 on 2019-10-07 19:26

from django.db import migrations, models
import testing.models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_auto_20190917_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Максимальный размер изображения 5 MB', upload_to='images', validators=[testing.models.FileSizeChecker(5)], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.PositiveIntegerField(default='1', verbose_name='Количестово баллов за полный ответ'),
        ),
        migrations.AlterField(
            model_name='test',
            name='points',
            field=models.PositiveIntegerField(default='0', verbose_name='Очки за частично правильные ответы'),
        ),
        migrations.AlterField(
            model_name='test',
            name='time',
            field=models.PositiveIntegerField(default='5', verbose_name='Время на тест'),
        ),
    ]
