# Generated by Django 2.2.5 on 2019-10-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_auto_20191007_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='full_correct',
            field=models.PositiveIntegerField(blank=True, default='0', editable=False, verbose_name='Полных ответов'),
        ),
        migrations.AddField(
            model_name='result',
            name='non_full_correct',
            field=models.PositiveIntegerField(blank=True, default='0', editable=False, verbose_name='Неполных ответов'),
        ),
    ]
