# Generated by Django 2.2.5 on 2020-03-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0010_auto_20191015_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Тест доступен для прохождения', verbose_name='Тест активен'),
        ),
    ]
